-- Ejecutar conectado a la base vectra_cure desde pgAdmin 4.

BEGIN;

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telefono VARCHAR(20) NOT NULL,
  rol VARCHAR(20) NOT NULL DEFAULT 'paciente',
  password_hash VARCHAR(255),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_usuarios_rol CHECK (rol IN ('paciente', 'medico', 'admin'))
);

CREATE TABLE perfiles_medicos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL UNIQUE
    REFERENCES usuarios(id) ON DELETE CASCADE,
  especialidad VARCHAR(50) NOT NULL,
  num_colegiatura VARCHAR(50) NOT NULL UNIQUE,
  verificado BOOLEAN NOT NULL DEFAULT FALSE,
  nombre_clinica VARCHAR(150) NOT NULL,
  direccion VARCHAR(255) NOT NULL,
  latitud NUMERIC(10,8) NOT NULL,
  longitud NUMERIC(11,8) NOT NULL,
  precio_aprox NUMERIC(10,2) NOT NULL,
  rating_promedio NUMERIC(3,2) NOT NULL DEFAULT 5.00,
  num_resenas INTEGER NOT NULL DEFAULT 0,
  foto VARCHAR(255),
  galeria JSONB,
  horario_atencion VARCHAR(100) NOT NULL DEFAULT '09:00 - 18:30',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_perfiles_latitud CHECK (latitud BETWEEN -90 AND 90),
  CONSTRAINT ck_perfiles_longitud CHECK (longitud BETWEEN -180 AND 180),
  CONSTRAINT ck_perfiles_precio CHECK (precio_aprox >= 0),
  CONSTRAINT ck_perfiles_rating CHECK (rating_promedio BETWEEN 0 AND 5),
  CONSTRAINT ck_perfiles_num_resenas CHECK (num_resenas >= 0)
);

CREATE INDEX ix_perfiles_especialidad_activo
  ON perfiles_medicos (especialidad, activo);

CREATE TABLE citas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medico_id INTEGER NOT NULL
    REFERENCES perfiles_medicos(id) ON DELETE RESTRICT,
  paciente_nombre VARCHAR(120) NOT NULL,
  paciente_email VARCHAR(100) NOT NULL,
  paciente_telefono VARCHAR(20) NOT NULL,
  fecha DATE NOT NULL,
  hora CHAR(5) NOT NULL,
  motivo TEXT,
  precio_aprox NUMERIC(10,2) NOT NULL,
  metodo_pago VARCHAR(30) NOT NULL,
  estado_pago VARCHAR(30) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADA',
  codigo_ticket VARCHAR(30) NOT NULL UNIQUE,
  motivo_cancelacion VARCHAR(255),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  turno_activo SMALLINT GENERATED ALWAYS AS (
    CASE WHEN estado IN ('CONFIRMADA', 'COMPLETADA') THEN 1 ELSE NULL END
  ) STORED,
  CONSTRAINT uq_citas_turno_activo UNIQUE (medico_id, fecha, hora, turno_activo),
  CONSTRAINT ck_citas_precio CHECK (precio_aprox >= 0),
  CONSTRAINT ck_citas_metodo_pago CHECK (
    metodo_pago IN ('PAYPAL_MOCK', 'EFECTIVO_VENTANILLA')
  ),
  CONSTRAINT ck_citas_estado_pago CHECK (
    estado_pago IN ('PAGADO_SIMULADO', 'PENDIENTE_VENTANILLA', 'REEMBOLSADO_SIMULADO')
  ),
  CONSTRAINT ck_citas_estado CHECK (
    estado IN ('CONFIRMADA', 'COMPLETADA', 'CANCELADA', 'NO_SHOW')
  )
);

CREATE INDEX ix_citas_telefono_fecha
  ON citas (paciente_telefono, fecha_creacion DESC);
CREATE INDEX ix_citas_estado_fecha
  ON citas (estado, fecha);

CREATE TABLE resenas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medico_id INTEGER NOT NULL
    REFERENCES perfiles_medicos(id) ON DELETE CASCADE,
  paciente_nombre VARCHAR(100) NOT NULL,
  calificacion SMALLINT NOT NULL,
  comentario TEXT,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_resenas_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

CREATE INDEX ix_resenas_medico_fecha
  ON resenas (medico_id, fecha_creacion DESC);

COMMIT;
