-- Migración V2 no destructiva. Ejecutar UNA vez sobre una base ya creada.
-- Hace las citas propiedad de una cuenta paciente y añade disponibilidad estructurada.

BEGIN;

ALTER TABLE citas ADD COLUMN IF NOT EXISTS paciente_usuario_id INTEGER;

UPDATE citas c
SET paciente_usuario_id = u.id
FROM usuarios u
WHERE c.paciente_usuario_id IS NULL
  AND lower(c.paciente_email) = lower(u.email)
  AND u.rol = 'paciente';

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM citas WHERE paciente_usuario_id IS NULL) THEN
    RAISE EXCEPTION 'Hay citas sin paciente_usuario_id. Corrige paciente_email o crea las cuentas antes de repetir la migración.';
  END IF;
END $$;

ALTER TABLE citas
  ALTER COLUMN paciente_usuario_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_citas_paciente_usuario') THEN
    ALTER TABLE citas ADD CONSTRAINT fk_citas_paciente_usuario
      FOREIGN KEY (paciente_usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_citas_paciente_fecha ON citas (paciente_usuario_id, fecha);

CREATE TABLE IF NOT EXISTS disponibilidades_medicas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_medico_id INTEGER NOT NULL REFERENCES perfiles_medicos(id) ON DELETE CASCADE,
  dia_semana SMALLINT NOT NULL,
  hora_inicio CHAR(5) NOT NULL,
  hora_fin CHAR(5) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT ck_disponibilidad_dia CHECK (dia_semana BETWEEN 0 AND 6),
  CONSTRAINT ck_disponibilidad_rango CHECK (hora_inicio < hora_fin),
  CONSTRAINT uq_disponibilidad_bloque UNIQUE (perfil_medico_id, dia_semana, hora_inicio, hora_fin)
);
CREATE INDEX IF NOT EXISTS ix_disponibilidad_perfil_dia_activo
  ON disponibilidades_medicas (perfil_medico_id, dia_semana, activo);

INSERT INTO disponibilidades_medicas (perfil_medico_id, dia_semana, hora_inicio, hora_fin, activo)
SELECT pm.id, d.dia_semana, d.hora_inicio, d.hora_fin, TRUE
FROM perfiles_medicos pm
CROSS JOIN (VALUES
  (0, '08:00', '18:00'), (1, '08:00', '18:00'), (2, '08:00', '18:00'),
  (3, '08:00', '18:00'), (4, '08:00', '18:00'), (5, '09:00', '13:00')
) AS d(dia_semana, hora_inicio, hora_fin)
ON CONFLICT (perfil_medico_id, dia_semana, hora_inicio, hora_fin) DO NOTHING;

COMMIT;
